Repository MakieOrg/Makie.jl, pull requests merged in 2022-03, with the labels that each got.

#1732 Move `show_axis` out of `scenekw`
  RPRMakie/test/lines.jl
  docs/examples/layoutables/lscene.md
  docs/examples/plotting_functions/volumeslices.md
Labels: bug

#1733 `volumeslices`: expose heatmaps
  docs/examples/plotting_functions/volumeslices.md
  src/basic_recipes/volumeslices.jl
Labels: enhancement

#1682 add function as `y` argument example
  docs/tutorials/basic-tutorial.md
Labels: documentation
