Repository MakieOrg/Makie.jl, pull requests merged in 2024-10, with the labels that each got.

#4434 fix heatmapshader for ranges
  ReferenceTests/src/tests/examples2d.jl
  src/basic_recipes/datashader.jl
  test/conversions.jl
Labels: skip-changelog

#4438 Low hanging fruit for a bit better precompile
  WGLMakie/Project.toml
  WGLMakie/src/display.jl
  WGLMakie/src/precompiles.jl
  WGLMakie/src/serialization.jl
  src/scenes.jl
Labels: skip-changelog

#4444 Fix local serve in ReferenceUpdater
  ReferenceUpdater/src/local_server.jl
Labels: skip-changelog

#4455 Update style.css
  docs/src/.vitepress/theme/style.css
Labels: skip-changelog

#4462 Fix RPR examples
  docs/src/explanations/backends/rprmakie.md
Labels: skip-changelog

#4468 Improvements to relocatability test script
  relocatability.jl
Labels: skip-changelog

#4431 More improvements for ReferenceUpdater
  .github/workflows/reference_tests.yml
  CairoMakie/test/runtests.jl
  GLMakie/test/runtests.jl
  ReferenceTests/src/database.jl
  ReferenceTests/src/runtests.jl
  ReferenceUpdater/Project.toml
  ReferenceUpdater/src/ReferenceUpdater.jl
  ReferenceUpdater/src/image_download.jl
  ReferenceUpdater/src/local_server.jl
  ReferenceUpdater/src/reference_images.html
  WGLMakie/test/runtests.jl
Labels: skip-changelog

#4467 WGLMakie relocatability
  CHANGELOG.md
  WGLMakie/src/picking.jl
  WGLMakie/src/serialization.jl
Labels: skip-changelog

#3922 Add code to fake interaction videos with blocks
  assets/cursor.png
  assets/cursor_pressed.png
  docs/fake_interaction.jl
  docs/makedocs.jl
  docs/src/reference/blocks/button.md
  docs/src/reference/blocks/intervalslider.md
  docs/src/reference/blocks/menu.md
  docs/src/reference/blocks/slidergrid.md
Labels: skip-changelog

#4480 Update GeoMakie image
  docs/src/assets/geomakie_example.png
Labels: skip-changelog

#4460 Update ecosystem.md
  docs/src/assets/beeswarm_example.png
  docs/src/ecosystem.md
Labels: skip-changelog

#4482 Refactor `Toggle` to use tick updates instead of an async task for the animation
  docs/fake_interaction.jl
  docs/src/reference/blocks/toggle.md
  src/makielayout/blocks/toggle.jl
Labels: skip-changelog

#4484 Fix upload of new refimages
  ReferenceUpdater/src/reference_images.html
Labels: skip-changelog

#4483 Add animated example for `Checkbox`
  docs/src/reference/blocks/checkbox.md
Labels: skip-changelog

#4433 Add reference image tests for untested plots/blocks
  ReferenceTests/src/tests/examples2d.jl
  ReferenceTests/src/tests/examples3d.jl
  ReferenceTests/src/tests/figures_and_makielayout.jl
  ReferenceTests/src/tests/short_tests.jl
Labels: skip-changelog

#4327 use InverseFunctions to invert functions
  Project.toml
  src/Makie.jl
  src/layouting/transformation.jl
  test/makielayout.jl
Labels: skip-changelog

#4487 Improve refimages
  ReferenceTests/src/tests/examples2d.jl
Labels: skip-changelog

#4490 Simplify gantt example with new barplot and legend features
  docs/src/reference/plots/barplot.md
Labels: skip-changelog

#4464 Fix adapted_grid failure
  .github/workflows/Docs.yml
  .github/workflows/ci.yml
  .github/workflows/compilation-benchmark.yaml
  .github/workflows/reference_tests.yml
  .github/workflows/rprmakie.yaml
  Project.toml
Labels: skip-changelog

#4504 Figure size and dpi how-to
  docs/Project.toml
  docs/makedocs.jl
  docs/src/explanations/figure.md
  docs/src/explanations/scenes.md
  docs/src/how-to/match-figure-size-font-sizes-and-dpi.md
Labels: skip-changelog

#4493 Benchmark simplification
  .github/workflows/compilation-benchmark.yaml
  metrics/ttfp/benchmark-ttfp.jl
  metrics/ttfp/run-benchmark.jl
Labels: skip-changelog

#4132 Improve CairoMakie's 2D mesh performance
  CHANGELOG.md
  CairoMakie/src/primitives.jl
Labels: CairoMakie

#4505 Move favicon and logo to where DocumenterVitepress expects them
  docs/src/public/favicon.ico
  docs/src/public/logo.png
  docs/src/public/logo.svg
Labels: skip-changelog

#4288 Test each backend for relocatability
  .github/workflows/relocatability.yml
  relocatability.jl
Labels: skip-changelog

#4523 Try temporary fix for WGLMakie CI
  WGLMakie/Project.toml
Labels: skip-changelog

#4515 Make benchmark plots and post a gist with them
  .github/workflows/compilation-benchmark.yaml
  metrics/ttfp/Project.toml
  metrics/ttfp/run-benchmark.jl
Labels: skip-changelog

#4541 Fix the docs build folder artifact
  .github/workflows/Docs.yml
Labels: skip-changelog

#4542 Fix CI slowdown by relying on new bonito version with new HTTP.jl
  WGLMakie/Project.toml
Labels: skip-changelog

#4548 Fix docstrings for 1.11
  MakieCore/src/recipes.jl
Labels: skip-changelog

#4546 Fix legend for plotlist with multiple plots
  CHANGELOG.md
  src/makielayout/blocks/legend.jl
  test/specapi.jl
Labels: Legend & Colorbar

#4553 Median ratio bootstrap plot for benchmarks
  metrics/ttfp/Project.toml
  metrics/ttfp/run-benchmark.jl
Labels: skip-changelog

#4555 Use ABBA pattern for benchmarking
  metrics/ttfp/run-benchmark.jl
Labels: skip-changelog
