Repository MakieOrg/Makie.jl, pull requests merged in 2024-11, with the labels that each got.

#4538 Improve closeall and renderloop task handling
  GLMakie/src/screen.jl
Labels: skip-changelog

#4564 rename Tesselation -> Tessellation
  RPRMakie/examples/makie_example.jl
  RPRMakie/src/meshes.jl
  ReferenceTests/src/tests/examples3d.jl
  WGLMakie/src/imagelike.jl
  docs/src/reference/plots/mesh.md
  src/basic_recipes/wireframe.jl
  src/utilities/utilities.jl
Labels: skip-changelog

#4485 fix low hanging fruits for render performance
  CairoMakie/src/infrastructure.jl
  GLMakie/src/GLAbstraction/GLRender.jl
  GLMakie/src/GLAbstraction/GLRenderObject.jl
  GLMakie/src/postprocessing.jl
  GLMakie/src/rendering.jl
  GLMakie/src/screen.jl
  src/layouting/transformation.jl
Labels: skip-changelog

#4578 Add second example to "boxes around subfigures how-to page"
  docs/src/how-to/draw-boxes-around-subfigures.md
Labels: skip-changelog

#4577 Add an example of using jupyter-server-proxy with WGLMakie
  docs/src/explanations/backends/wglmakie.md
Labels: documentation, WGLMakie

#4612 Add informative error if invalid side is used for violin
  src/stats/violin.jl
Labels: skip-changelog

#4557 more thoroughly test session + server to figure out the problem with …
  WGLMakie/test/runtests.jl
Labels: skip-changelog

#4615 Fix Float32 constraints in poly pipeline
  CHANGELOG.md
  src/basic_recipes/poly.jl
  test/poly.jl
  test/runtests.jl
Labels: bug, mesh
