Repository MakieOrg/Makie.jl, pull requests merged in 2024-07, with the labels that each got.

#4003 Fix CI
  ReferenceTests/src/tests/examples2d.jl
Labels: skip-changelog

#3909 Fix projection from clip to data space
  CHANGELOG.md
  src/camera/projection_math.jl
  test/projection_math.jl
Labels: bug, Makie

#4034 Docs version picker
  docs/buildutils/deploydocs.jl
  docs/src/.vitepress/config.mts
  docs/src/.vitepress/theme/VersionPicker.vue
  docs/src/.vitepress/theme/index.ts
Labels: skip-changelog

#4035 Sort versions in picker newest to oldest
  docs/buildutils/deploydocs.jl
Labels: skip-changelog

#4050 Fix docs, move SA to head
  docs/src/.vitepress/config.mts
  docs/src/.vitepress/theme/SimpleAnalytics.vue
  docs/src/.vitepress/theme/index.ts
Labels: skip-changelog

#4040 make the backend choice more clear
  docs/src/index.md
Labels: skip-changelog

#4051 fix stackoverflow for convert_single_argument(Any[])
  src/conversions.jl
  test/conversions.jl
Labels: skip-changelog

#3954 Improve accuracy of set framerate in GLMakie
  CHANGELOG.md
  GLMakie/src/GLMakie.jl
  GLMakie/src/screen.jl
  src/Makie.jl
  src/utilities/timing.jl
  test/timing.jl
Labels: GLMakie
