Repository MakieOrg/Makie.jl, pull requests merged in 2024-08, with the labels that each got.

#3980 move throttle_function to Bonito
  WGLMakie/Project.toml
  WGLMakie/src/wglmakie.bundled.js
  WGLMakie/src/wglmakie.js
Labels: skip-changelog

#4089 fix stairs type to match the input
  src/basic_recipes/stairs.jl
Labels: skip-changelog

#4100 fix visible update for plots inserted after scene
  GLMakie/src/drawing_primitives.jl
  GLMakie/src/screen.jl
Labels: skip-changelog

#4104 Fix outline for image scatter
  WGLMakie/assets/sprites.frag
Labels: skip-changelog

#4105 Follow up #4062, fix missed changes in merge commits
  GLMakie/src/screen.jl
Labels: skip-changelog

#4106 require version in bug report
  .github/ISSUE_TEMPLATE/bug-report-.md
Labels: skip-changelog

#4114 Fix test failures
  GLMakie/test/runtests.jl
  test/Plane.jl
  test/float32convert.jl
Labels: skip-changelog

#4117 Fix GLMakie shader compatibility problems with arrays of arrays
  GLMakie/assets/shader/sprites.geom
  GLMakie/assets/shader/sprites.vert
Labels: skip-changelog

#2776 Details for (de)activating default interactions
  docs/src/reference/blocks/axis.md
Labels: skip-changelog

#4096 Update datashader docs
  docs/src/reference/plots/datashader.md
Labels: documentation, skip-changelog

#4147 fix step for 1d heatmap
  src/conversions.jl
  test/conversions.jl
Labels: skip-changelog

#4177 Add the `display` error message when no backend is loaded to `save`
  CHANGELOG.md
  src/display.jl
Labels: Makie

#4143 Avoid deprecated bindings on re-exported items
  src/deprecated.jl
Labels: skip-changelog
