Repository MakieOrg/Makie.jl, pull requests merged in 2024-02, with the labels that each got.

#3605 Check converted as well as input args in polygon drawing in CairoMakie
  CHANGELOG.md
  CairoMakie/src/overrides.jl
  CairoMakie/test/Project.toml
  CairoMakie/test/rasterization_tests.jl
  CairoMakie/test/svg_tests.jl
Labels: CairoMakie

#3635 Add links to urls in `Docs/Backends/WGLMakie`
  docs/explanations/backends/wglmakie.md
Labels: skip-changelog

#3633 Fix potential bugs with format strings
  CHANGELOG.md
  Project.toml
  src/makielayout/MakieLayout.jl
  src/makielayout/blocks/slidergrid.jl
  src/makielayout/helpers.jl
  src/makielayout/lineaxis.jl
  src/makielayout/types.jl
Labels: enhancement

#3592 Add example of horizontal orientation to violin
  docs/reference/plots/barplot.md
  docs/reference/plots/boxplot.md
  docs/reference/plots/violin.md
Labels: skip-changelog

#3615 Fix `rich` rticks for `PolarAxis`
  CHANGELOG.md
  ReferenceTests/src/tests/figures_and_makielayout.jl
  src/makielayout/blocks/polaraxis.jl
Labels: bug, rich text

#3646 Added doc on Makie package extension
  docs/explanations/recipes.md
Labels: skip-changelog

#3656 Update translate! documentation
  src/layouting/transformation.jl
Labels: skip-changelog

#3657 Add compat bound on `FFMPEG_jll`
  Project.toml
Labels: skip-changelog
