Repository MakieOrg/Makie.jl, pull requests merged in 2024-05, with the labels that each got.

#3808 add `axislegend` method that inputs an axis and a title
  CHANGELOG.md
  src/makielayout/blocks/legend.jl
  test/makielayout.jl
Labels: bug

#3819 document `WilkinsonTicks`
  CHANGELOG.md
  src/makielayout/ticklocators/wilkinson.jl
  src/makielayout/types.jl
Labels: documentation

#3824 Add docstrings to bezier path building blocks
  docs/reference/plots/scatter.md
  src/bezier.jl
Labels: skip-changelog

#3695 add recipes for intervals
  CHANGELOG.md
  src/Makie.jl
  src/basic_recipes/band.jl
  src/basic_recipes/error_and_rangebars.jl
  src/basic_recipes/hvspan.jl
  test/conversions.jl
Labels: enhancement

#3696 support intervals for setting limits
  CHANGELOG.md
  src/makielayout/blocks/axis.jl
  src/makielayout/blocks/axis3d.jl
  test/makielayout.jl
Labels: enhancement

#3834 revert CI changes
  .github/workflows/ci.yml
  .github/workflows/reference_tests.yml
  .github/workflows/relocatability.yml
  .github/workflows/rprmakie.yaml
Labels: skip-changelog

#3838 add compats for new deps
  MakieCore/Project.toml
Labels: skip-changelog

#3846 Row-first printing of available attribute
  MakieCore/src/recipes.jl
Labels: skip-changelog

#3844 Update colors.md
  docs/explanations/colors.md
Labels: skip-changelog

#3848 Improve `markersize` docstring
  MakieCore/src/basic_plots.jl
Labels: skip-changelog

#3866 Support glow for text (fixes for #3858)
  MakieCore/src/basic_plots.jl
  ReferenceTests/src/tests/examples3d.jl
  WGLMakie/src/particles.jl
Labels: skip-changelog

#3697 support the loop option in html video output
  CHANGELOG.md
  src/ffmpeg-util.jl
  src/recording.jl
  test/record.jl
Labels: enhancement

#3870 fix hist(..., gap = 0.1)
  ReferenceTests/src/tests/examples2d.jl
  src/stats/hist.jl
Labels: skip-changelog

#3872 fix RPRMakie with Material
  RPRMakie/examples/bars.jl
  RPRMakie/src/meshes.jl
Labels: skip-changelog

#3884 Fix stable docs with shortened version number in DocumenterVitepress
  docs/makedocs.jl
Labels: skip-changelog

#3892 Refactor examples
  docs/attrdocs_block.jl
  docs/src/reference/plots/scatter.md
  src/Makie.jl
  src/basic_recipes/makiecore_examples/scatter.jl
  src/makielayout/blocks.jl
  src/makielayout/blocks/axis.jl
  src/makielayout/blocks/axis3d.jl
  src/makielayout/blocks/box.jl
  src/makielayout/blocks/legend.jl
Labels: skip-changelog

#3894 Add more redirects from previous urls
  docs/makedocs.jl
Labels: skip-changelog

#3895 fix #3887 and fix #3869 (unbound var in tuple conversion)
  src/conversions.jl
Labels: skip-changelog
