Repository MakieOrg/Makie.jl, pull requests merged in 2025-02, with the labels that each got.

#4711 Reorganize Makie test files
  WGLMakie/src/events.jl
  src/utilities/timing.jl
  test/SceneLike/PolarAxis.jl
  test/SceneLike/figures.jl
  test/SceneLike/makielayout.jl
  test/SceneLike/scenes.jl
  test/conversions/cameras.jl
  test/conversions/conversions.jl
  test/conversions/convert_arguments.jl
  test/conversions/convert_attributes.jl
  test/conversions/dim-converts.jl
  test/conversions/float32convert.jl
  test/conversions/projection_math.jl
  test/conversions/transformations.jl
  test/events.jl
  test/interactivity/Axis.jl
  test/interactivity/Axis3.jl
  test/interactivity/MouseStateMachine.jl
  test/interactivity/camera_controls.jl
  test/interactivity/events.jl
  test/isolated/Plane.jl
  test/isolated/bezier.jl
  test/isolated/observables.jl
  test/isolated/patterns.jl
  test/isolated/quaternions.jl
  test/isolated/timing.jl
  test/plots/barplot.jl
  test/plots/hist.jl
  test/plots/poly.jl
  test/plots/primitives.jl
  test/plots/statistical_tests.jl
  test/plots/text.jl
  test/plots/voronoiplot.jl
  test/runtests.jl
  test/zoom_pan.jl
Labels: skip-changelog

#4776 Fix function signatures in docstrings
  src/event-recorder.jl
Labels: skip-changelog

#4775 Fix markdown list in docstring
  src/ffmpeg-util.jl
Labels: skip-changelog

#4805 Fix misslabeled refimg test from #4758
  ReferenceTests/src/tests/primitives.jl
Labels: skip-changelog

#4787 Add documentation on mesh normal generation
  docs/src/reference/plots/mesh.md
Labels: skip-changelog

#4780 Use sources attribute in docs/Project.toml
  docs/Project.toml
  docs/makedocs.jl
Labels: skip-changelog

#4820 Fix typos in UnitfulConversion() documentation
  src/dim-converts/unitful-integration.jl
Labels: documentation, skip-changelog

#4744 Curvilinear `contourf`
  CHANGELOG.md
  ReferenceTests/src/tests/examples2d.jl
  docs/src/reference/plots/contourf.md
  src/basic_recipes/contourf.jl
Labels: enhancement, (tri)contour(f)

#4783 Fix image name collision in docs
  docs/figure_block.jl
Labels: skip-changelog

#4825 Update `xlabel` to `ylabel` in UnitfulConversion documentation.
  src/dim-converts/unitful-integration.jl
Labels: skip-changelog

#4826 prepare 0.22.2
  CHANGELOG.md
  CairoMakie/Project.toml
  GLMakie/Project.toml
  MakieCore/Project.toml
  Project.toml
  RPRMakie/Project.toml
  WGLMakie/Project.toml
  src/makielayout/blocks/legend.jl
  test/SceneLike/makielayout.jl
Labels: skip-changelog
