Repository MakieOrg/Makie.jl, pull requests merged in 2025-06, with the labels that each got.

#5038 Fix code block in specapi docs
  docs/src/explanations/specapi.md
Labels: documentation, skip-changelog

#5031 include float32convert refimg tests
  ReferenceTests/src/tests/float32_conversion.jl
  ReferenceTests/src/tests/refimages.jl
  src/basic_recipes/error_and_rangebars.jl
  src/basic_recipes/poly.jl
Labels: skip-changelog

#5075 Cleanup compute graph constants
  CairoMakie/src/image-hmap.jl
  CairoMakie/src/lines.jl
  ComputePipeline/src/ComputePipeline.jl
  GLMakie/src/new-primitives.jl
  Makie/src/basic_recipes/text.jl
  Makie/src/camera/camera.jl
  Makie/src/utilities/texture_atlas.jl
  WGLMakie/src/plot-primitives.jl
Labels: skip-changelog

#5067 Improve performance a bit
  ComputePipeline/src/ComputePipeline.jl
  Makie/src/compute-plots.jl
  WGLMakie/src/serialization.jl
Labels: skip-changelog

#5079 use map! more instead of register_computation!
  Makie/src/basic_recipes/voxels.jl
  Makie/src/camera/camera.jl
  Makie/src/compute-plots.jl
  Makie/src/lighting.jl
  WGLMakie/src/plot-primitives.jl
  WGLMakie/src/voxel.jl
Labels: skip-changelog

#5077 Cleanup some TODO comments
  CairoMakie/src/mesh.jl
  CairoMakie/src/scatter.jl
  ComputePipeline/src/ComputePipeline.jl
  ComputePipeline/test/unit_tests.jl
  GLMakie/src/glshaders/lines.jl
  GLMakie/src/new-primitives.jl
  GLMakie/src/screen.jl
  GLMakie/test/unit_tests.jl
  Makie/precompile/shared-precompile.jl
  Makie/src/backend-functionality.jl
  Makie/src/basic_plots.jl
  Makie/src/basic_recipes/voxels.jl
  Makie/src/compute-plots.jl
  Makie/src/conversions.jl
  Makie/src/interfaces.jl
  Makie/src/lighting.jl
  Makie/src/specapi.jl
  Makie/src/utilities/texture_atlas.jl
  Makie/test/plots/primitives.jl
  ReferenceUpdater/src/ReferenceUpdater.jl
  ReferenceUpdater/src/image_download.jl
  WGLMakie/src/plot-primitives.jl
  WGLMakie/src/voxel.jl
Labels: skip-changelog

#5081 More docs updates for compute
  docs/src/explanations/inspector.md
  docs/src/explanations/observables.md
  docs/src/index.md
  docs/src/reference/blocks/polaraxis.md
  docs/src/reference/generic/transformations.md
Labels: skip-changelog

#5087 fix some typos
  .github/workflows/codespell.yml
  Makie/src/basic_recipes/arrows.jl
  Makie/src/basic_recipes/text.jl
  Makie/src/compute-plots.jl
  Makie/test/pipeline.jl
  ReferenceTests/src/tests/updating.jl
  WGLMakie/src/plot-primitives.jl
Labels: nfc

#5092 fix test paths, `test/Project.toml` and some typos
  CairoMakie/Project.toml
  CairoMakie/test/Project.toml
  ComputePipeline/Project.toml
  ComputePipeline/src/ComputePipeline.jl
  ComputePipeline/test/Project.toml
  GLMakie/src/GLAbstraction/GLAbstraction.jl
  GLMakie/test/Project.toml
  Makie/Project.toml
  MakieRecipes/Project.toml
  MakieRecipes/test/Project.toml
  WGLMakie/Project.toml
  WGLMakie/test/Project.toml
  docs/Project.toml
Labels: bug, skip-changelog

#5080 fix redisplaying fig after closing
  .github/workflows/relocatability.yml
  ComputePipeline/src/ComputePipeline.jl
  GLMakie/src/screen.jl
  Makie/src/Makie.jl
  Makie/src/basic_recipes/timeseries.jl
  Makie/src/display.jl
  Makie/src/scenes.jl
  Makie/src/utilities/texture_atlas.jl
  Makie/src/utilities/timing.jl
  Makie/test/isolated/timing.jl
  WGLMakie/src/WGLMakie.jl
  WGLMakie/src/display.jl
  WGLMakie/src/javascript/WGLMakie.bundled.js
  WGLMakie/src/javascript/WGLMakie.js
  WGLMakie/src/plot-primitives.jl
  WGLMakie/src/precompiles.jl
  WGLMakie/test/runtests.jl
  docs/makedocs.jl
Labels: skip-changelog

#5090 Clean up GLMakie errors a bit
  GLMakie/src/GLAbstraction/GLAbstraction.jl
  GLMakie/src/GLAbstraction/GLBuffer.jl
  GLMakie/src/GLAbstraction/GLRender.jl
  GLMakie/src/GLAbstraction/GLTexture.jl
  GLMakie/src/GLAbstraction/GLTypes.jl
  GLMakie/src/GLMakie.jl
  GLMakie/src/screen.jl
  GLMakie/test/runtests.jl
Labels: skip-changelog

#5104 restrict computepipeline version
  CHANGELOG.md
  Makie/LICENSE.md
  Makie/Project.toml
Labels: skip-changelog

#5117 dont convert dicts to attributes
  CHANGELOG.md
Labels: skip-changelog

#5133 fix arrows test not working as intended
  ReferenceTests/src/tests/examples2d.jl
Labels: skip-changelog
