Repository MakieOrg/Makie.jl, pull requests merged in 2025-04, with the labels that each got.

#4844 Add tutorial on pixel perfect image/heatmap plots
  docs/makedocs.jl
  docs/src/tutorials/pixel-perfect-rendering.md
Labels: skip-changelog

#4813 always forward parent attributes
  src/specapi.jl
Labels: skip-changelog

#4836 Show `axislegend(merge=true)` in errorbar docs
  docs/src/reference/plots/errorbars.md
Labels: documentation, skip-changelog

#4556 add `codespell` action
  .github/workflows/codespell.yml
  .github/workflows/enforce_news.yml
  CHANGELOG.md
  CairoMakie/src/primitives.jl
  CairoMakie/src/utils.jl
  GLMakie/experiments/shaderabstr.jl
  GLMakie/src/GLAbstraction/GLInfo.jl
  GLMakie/src/GLAbstraction/GLTexture.jl
  GLMakie/src/screen.jl
  ReferenceTests/src/tests/generic_components.jl
  ReferenceTests/src/tests/updating.jl
  ReferenceUpdater/src/local_server.jl
  WGLMakie/src/display.jl
  docs/src/explanations/conversion_pipeline.md
  docs/src/explanations/specapi.md
  docs/src/reference/blocks/axis.md
  docs/src/reference/plots/datashader.md
  metrics/ttfp/run-benchmark.jl
  src/basic_recipes/contourf.jl
  src/colorsampler.jl
  src/conversions.jl
  src/interfaces.jl
  src/makielayout/interactions.jl
  src/makielayout/lineaxis.jl
  src/scenes.jl
  src/specapi.jl
  src/utilities/texture_atlas.jl
  test/specapi.jl
  test/updating.jl
Labels: CI

#4910 Add syntax highlight tags to fenced code blocks
  src/interfaces.jl
  src/makielayout/helpers.jl
  src/makielayout/mousestatemachine.jl
  src/makielayout/types.jl
  src/theming.jl
  src/types.jl
Labels: skip-changelog

#4920 Generic float conversion
  src/dim-converts/unitful-integration.jl
Labels: skip-changelog

#4908 Fix markdown list in docs and docstrings
  docs/src/explanations/backends/glmakie.md
  src/ffmpeg-util.jl
  src/stats/hist.jl
Labels: skip-changelog
